# Generated by Django 4.1.7 on 2023-03-08 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=45)),
                ('nome', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('senha', models.CharField(max_length=45)),
                ('telefone', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=45)),
                ('created', models.DateTimeField()),
                ('pessoa_cpf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residuo.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Residuo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residuo.categoria')),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residuo.solicitacao')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=45)),
                ('numero', models.CharField(max_length=45)),
                ('bairro', models.CharField(max_length=45)),
                ('cidade', models.CharField(max_length=45)),
                ('cep', models.CharField(max_length=45)),
                ('estado', models.CharField(max_length=45)),
                ('pessoa_cpf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residuo.pessoa')),
            ],
        ),
    ]
