# Generated by Django 4.1.7 on 2023-06-06 19:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_cpf_cnpj.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=255, verbose_name='Logradouro')),
                ('numero', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('bairro', models.CharField(max_length=255, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=255, verbose_name='Cidade')),
                ('cep', models.CharField(max_length=8, verbose_name='CEP')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado')),
                ('tipo_logradouro', models.CharField(max_length=255, verbose_name='Tipo de Logradouro')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', django_cpf_cnpj.fields.CPFField(max_length=14)),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('email', models.EmailField(max_length=255, verbose_name='E-mail')),
                ('telefone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Telefone de contato', max_length=128, region=None, verbose_name='Telefone')),
            ],
        ),
        migrations.CreateModel(
            name='Residuo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_residuo', models.CharField(max_length=255, verbose_name='Nome do Resíduo')),
                ('peculiosidade', models.CharField(choices=[('Perigoso', 'Perigoso'), ('Não Perigoso', 'Não Perigoso')], max_length=255, verbose_name='Peculiosidade')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residuo.categoria', verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=45, verbose_name='Status')),
                ('data_solicitacao', models.DateField(verbose_name='Data da Solicitação')),
                ('hora', models.TimeField(verbose_name='Hora')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residuo.endereco', verbose_name='Endereço')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residuo.pessoa', verbose_name='Pessoa')),
                ('residuo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residuo.residuo', verbose_name='Resíduo')),
            ],
        ),
    ]
