# Generated by Django 4.1.7 on 2023-03-24 12:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_cpf_cnpj.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=255)),
                ('numero', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('bairro', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=255)),
                ('cep', models.CharField(max_length=8)),
                ('estado', models.CharField(max_length=2)),
                ('tipo_logradouro', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', django_cpf_cnpj.fields.CPFField(max_length=14)),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('telefone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Telefone de contato', max_length=128, region=None)),
            ],
        ),
        migrations.CreateModel(
            name='Residuo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_residuo', models.CharField(max_length=255)),
                ('peculiosidade', models.CharField(choices=[('Perigoso', 'Perigoso'), ('Não Perigoso', 'Não Perigoso')], max_length=255)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residuo.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=45)),
                ('data_solicitacao', models.DateField()),
                ('hora', models.TimeField()),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residuo.endereco')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residuo.pessoa')),
                ('residuo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residuo.residuo')),
            ],
        ),
    ]
