# Generated by Django 4.1.7 on 2023-03-17 22:47

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('residuo', '0002_alter_pessoa_cpf_alter_pessoa_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='telefone',
            field=phone_field.models.PhoneField(blank=True, help_text='Telefone de contato', max_length=31),
        ),
    ]
